project:
  type: website
  output-dir: docs

filters:
  - shinylive

website:
  title: "ROPESHubDashboard"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - dashboard.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



